NewsDotNet.WebUI/Areas/Admin/Controllers/AdminArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsDotNet.DomainModel.Entities;
using NewsDotNet.DomainModel.Abstract;
using NewsDotNet.WebUI.Areas.Admin.Mappers;
using NewsDotNet.WebUI.Areas.Admin.Models;
using Ninject;
using System.Text;
using System.IO;

namespace NewsDotNet.WebUI.Areas.Admin.Controllers
{
    public class AdminArticlesController : Controller
    {
        private IArticlesRepository _articleRepo;
        private ITagsRepository _tagsRepo;
        private IMapper _modelMapper;

        public AdminArticlesController(IArticlesRepository articleRepo, ITagsRepository tagsRepo, IMapper modelMapper)
        {
            _articleRepo = articleRepo;
            _tagsRepo = tagsRepo;
            _modelMapper = modelMapper;
        }

        [HttpGet]
        public ActionResult New()
        {
            var article = new ArticleViewModel();
            ViewBag.Action = ActionType.NewArticle;
            return View("ArticleEditor", article);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult New(ArticleViewModel newArticleView, HttpPostedFileBase titleImage)
        {
            CheckAddressNameAvailability(newArticleView.AddressName, newArticleView.Id);
            if (null == titleImage)
                ModelState.AddModelError("TitleImagePath", "Прикрепите к статье изображение");
            if (ModelState.IsValid)
            {
                var article = _modelMapper.Map<ArticleViewModel, Article>(newArticleView);
                article.CreatedTime = DateTime.Now;
                article.LastChangedTime = DateTime.Now;
                article.Tags = TagStringToList(newArticleView.TagsString);
                SaveUploadedImage(article, titleImage);
                _articleRepo.Add(article);
                return RedirectToAction("Manage", "AdminHome");
            }
            ViewBag.Action = ActionType.NewArticle;
            return View("ArticleEditor", newArticleView);
        }

        [HttpGet]
        public ActionResult Edit(string addressName)
        {
            var article = _articleRepo.GetByAddressName(addressName);
            if (null == article)
                return HttpNotFound();
            var articleView = _modelMapper.Map<Article, ArticleViewModel>(article);
            articleView.TagsString = TagListToString(article.Tags);
            ViewBag.Action = ActionType.EditArticle;
            return View("ArticleEditor", articleView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(ArticleViewModel articleView, HttpPostedFileBase titleImage)
        {
            CheckAddressNameAvailability(articleView.AddressName, articleView.Id);
            if (ModelState.IsValid)
            {
                var article = _modelMapper.Map<ArticleViewModel, Article>(articleView);
                article.Tags = TagStringToList(articleView.TagsString);
                article.LastChangedTime = DateTime.Now;
                SaveUploadedImage(article, titleImage);
                _articleRepo.Update(article);
                return RedirectToAction("Manage", "AdminHome");
            }
            ViewBag.Action = ActionType.EditArticle;
            return View("ArticleEditor", articleView);
        }

        private string TagListToString(ICollection<Tag> tags)
        {
            if (tags.Count == 0)
                return String.Empty;
            StringBuilder builder = new StringBuilder();
            foreach(var tag in tags)
            {
                builder.AppendFormat("{0}, ", tag.Name);
            }
            builder.Remove(builder.Length - 2, 2);
            return builder.ToString();
        }

        private ICollection<Tag> TagStringToList(string tagString)
        {
            List<Tag> tags = new List<Tag>();
            if (!String.IsNullOrWhiteSpace(tagString))
            {
                var tagArray = tagString.Split(',');
                foreach (var s in tagArray)
                {
                    if (!String.IsNullOrWhiteSpace(s))
                    {
                        string name = s.Trim();
                        Tag t = _tagsRepo.GetByName(name);
                        if (null == t)
                            t = _tagsRepo.Add(new Tag { Name = name });
                        tags.Add(t);
                    }
                }
            }
            return tags;
        }

        private void SaveUploadedImage(Article article, HttpPostedFileBase image)
        {
            string newPath;
            string oldPath = article.TitleImagePath;
            bool pathChanged = !isOldImagePathRelevant(oldPath, article.AddressName);
            FileInfo oldImageInfo = null;
            if (pathChanged)
                oldImageInfo = new FileInfo(Server.MapPath(oldPath));
            if (null == image)
            {
                if (pathChanged)
                {   //there is an old image and article address changed => rename old image
                    newPath = String.Format("~/Content/Images/Articles/{0}{1}",
                                        article.AddressName,
                                        oldImageInfo.Extension);
                    oldImageInfo.MoveTo(newPath);
                }
                else
                    return;
            }
            else
            {   //there is a new image => save new image
                FileInfo newImageInfo = new FileInfo(image.FileName);
                newPath = String.Format("~/Content/Images/Articles/{0}{1}",
                                            article.AddressName,
                                            newImageInfo.Extension);
                image.SaveAs(Server.MapPath(newPath));

                if (pathChanged)
                {   //path changed and there is an old image => delete old image
                    oldImageInfo.Delete();
                }
            }
            article.TitleImagePath = newPath;
        }

        private void CheckAddressNameAvailability(string addressName, int id)
        {
            var existingArticle = _articleRepo.GetByAddressName(addressName);
            if (null != existingArticle && existingArticle.Id != id)
                ModelState.AddModelError("addressName", "Данный адрес уже принадлежит другой статье");
        }

        private bool isOldImagePathRelevant(string imagePath, string articleAddressName)
        {
            if (null == imagePath)
                return true;
            FileInfo info = new FileInfo(imagePath);
            string name = info.Name.Remove(info.Name.LastIndexOf('.'));
            return name.Equals(articleAddressName);
        }
    }

    public enum ActionType
    {
        NewArticle,
        EditArticle
    }
}

NewsDotNet.WebUI/Areas/Admin/Views/AdminArticles/ArticleEditor.cshtml
@using NewsDotNet.WebUI.Areas.Admin.Controllers
@model NewsDotNet.WebUI.Areas.Admin.Models.ArticleViewModel

@{
    ActionType action = ViewBag.Action;
    ViewBag.Title = action == ActionType.NewArticle ? "Новая статья" : "Редактирование статьи";
}

@using (Html.BeginForm(action == ActionType.NewArticle ? "New" : "Edit",
                        "AdminArticles",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal container">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CreatedTime)
        @Html.HiddenFor(model => model.TitleImagePath)

        <div class="form-group">
            <label class="control-label col-md-2">Заголовок</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Адрес</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Изображение</label>
            <div class="col-md-10">
                <input type="file" name="titleImage" accept=".jpg,.png,.jpeg,.gif" />
                @Html.ValidationMessageFor(model => model.TitleImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Тело статьи</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Теги</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TagsString, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.TagsString, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Состояние</label>
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.State, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Manage", "AdminHome")
</div>

<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
<script src="~/Content/jquery-tags-input/jquery.tagsinput.min.js"></script>
<link rel="stylesheet" type="text/css" href="~/Content/jquery-tags-input/jquery.tagsinput.min.css" />
<script type="text/javascript">
    var editor = CKEDITOR.instances['Body'];
    if (editor) { editor.destroy(true); }
    CKEDITOR.replace('Body', {
        enterMode: CKEDITOR.ENTER_BR,
    });

    $('#TagsString').tagsInput({ 'width': '100%', 'maxChars': 20, 'defaultText': 'добавить тег' });
</script>