NewsDotNet.WebUI/Areas/Admin/Controllers/AdArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsDotNet.DomainModel.Abstract;
using NewsDotNet.DomainModel.Entities;
using Newtonsoft.Json;
using NewsDotNet.WebUI.Models;

namespace NewsDotNet.WebUI.Areas.Admin.Controllers
{
    public class AdArticlesController : Controller
    {
        private IArticlesRepository _articlesRepo;
        
        public AdArticlesController(IArticlesRepository articlesRepo)
        {
            _articlesRepo = articlesRepo;
        }

        public ActionResult List(IEnumerable<int> articleIds)
        {
            //seletct only articles with ids form the list
            var result = _articlesRepo.All().Where(article => articleIds.Any(id => id == article.Id));

            var jsonSettings = new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

            var convertedResult = JsonConvert.SerializeObject(result, jsonSettings);

            return Content(convertedResult, "application/json");
        }

        public ActionResult PagingList(int page = 1, int itemsPerPage = 10)
        {
            var articles = _articlesRepo.All().Skip((page - 1) * itemsPerPage).Take(itemsPerPage);
            var pagingInfo = new PagingInfo{
                CurrentPage = page,
                ItemsPerPage = itemsPerPage,
                TotalItems = _articlesRepo.All().Count()
            };

            var result = new ArticleListViewModel{
                Articles = articles,
                PagingInfo = pagingInfo
            };

            var jsonSettings = new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

            var convertedResult = JsonConvert.SerializeObject(result, jsonSettings);
            return Content(convertedResult, "application/json");            
        }

	}
}

NewsDotNet.WebUI/Areas/Admin/Controllers/IssueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsDotNet.DomainModel.Entities;
using NewsDotNet.DomainModel.Abstract;

namespace NewsDotNet.WebUI.Areas.Admin.Controllers
{
    public class IssueController : Controller
    {
        IMainPageEntitiesRepository _mainPageRepo;
        IArticlesRepository _articlesRepo;

        public IssueController(IMainPageEntitiesRepository mainPageRepo, IArticlesRepository articlesRepo)
        {
            _mainPageRepo = mainPageRepo;
            _articlesRepo = articlesRepo;
        }
        //
        // GET: /Admin/Issue/
        public ActionResult Index()
        {
            return View(_mainPageRepo.All().Where(e => !e.IsFeatured).ToList());
        }


        [HttpPost]
        public ActionResult Save(IEnumerable<MainPageEntity> newEntities)
        {
            _mainPageRepo.Clear();
            if (newEntities != null)
            {
                _mainPageRepo.Add(newEntities); 
            }
            return new JsonResult { Data = new { result = "OK" } };
        }
	}
}

NewsDotNet.WebUI/Areas/Admin/Views/Issue/ArticleTile.cshtml
@model NewsDotNet.DomainModel.Entities.MainPageEntity

<li data-id="@Model.ArticleID" data-col="@Model.GridData.Col" data-row="@Model.GridData.Row" data-sizex="@Model.GridData.SizeX" data-sizey="@Model.GridData.SizeY">
    <button type="button" class="close"><span aria-hidden="true">&times;</span></button>
    <img src="@Url.Content(Model.Article.TitleImagePath)">
    <div class="post-info">
        <div class="post-basic-info">
            <h3>@Model.Article.Title</h3>
            @foreach (var tag in Model.Article.Tags)
            {
                <span><a href="#"><label> </label>@tag.Name</a></span>
            }
            <p>@Html.Raw(Model.Article.Body)</p>
        </div>
    </div>
</li>

NewsDotNet.WebUI/Areas/Admin/Views/Issue/Index.cshtml
@model IEnumerable<NewsDotNet.DomainModel.Entities.MainPageEntity>

@{
    ViewBag.Title = "News.NET - формирование главной страницы";
}


<link href="~/Content/Styles/main.css" rel="stylesheet" />
<link href="~/Content/Styles/jquery.gridster.css" rel="stylesheet" />
<script src="~/Scripts/jquery.gridster.js"></script>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#article-select">Добавить статьи</button>
            <button class="btn btn-warning" onclick="clearGrid();">Очистить</button>
            <button class="btn btn-primary pull-right" onclick="save();">Сохранить</button>
        </h3>
        <div class="btn-group pull-right">

        </div>
    </div>
    <div class="panel-body">
        <ul id="tiles" class="gridster">
            @foreach(var entity in Model)
            {
                @Html.Partial("ArticleTile", entity);
            }
        </ul>
    </div>
</div>

@*Modal window*@
<div class="modal fade" id="article-select" tabindex="-1" role="dialog" aria-hidden="true" aria-labelledby="modalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button"class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalLabel">Выберете статьи</h4>
            </div>
            <div class="modal-body">
                <nav>
                    <ul class="pagination">

                    </ul>
                </nav>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th><input type="checkbox" id="select-all" onclick="checkAll();" /></th>
                            <th>Название</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <nav>
                    <ul class="pagination">

                    </ul>
                </nav>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" type="button" data-dismiss="modal">Отмена</button>
                <button class="btn btn-primary" type="button" data-dismiss="modal" onclick="addArticles();">Добавить</button>  
            </div>
        </div>
    </div>
</div>

@*Scripts goes here*@
<script type="text/javascript">
    $(function () {
        var containerWidth = $('.container').width();

        var baseWidth = (containerWidth - 70) / 7;

        $("#tiles").gridster({
            widget_margins: [10, 10],
            widget_base_dimensions: [baseWidth, baseWidth * 1.3],
            avoid_overlapped_widgets:true,
            resize: {
                enabled: true,
                stop: adjustFontSize
            },
            serialize_params: function ($w, wgd) {
                return {
                    ArticleID: $($w).attr('data-id'),
                    IsFeatured: false,
                    GridData: {
                        Col: wgd.col,
                        Row: wgd.row,
                        SizeX: wgd.size_x,
                        SizeY: wgd.size_y
                    }
                }
            }
        });

        $('#tiles li').each(function () {
            adjustFontSize(null, null, $(this));
        })

        $('#alert-box').hide();

        SetupCloseButtons();
    });

    $('#article-select').on('show.bs.modal', function (event) {
        @*var modal = $('#article-select .modal-body');
        modal.empty();
        modal.load("@Url.Action("ArticleTable")");*@
        loadArticleList(1);
    });

    function checkAll() {
       
        $('.modal tbody input:checkbox').prop('checked',$('input#select-all').prop('checked'));
    }

    function SetupCloseButtons() {
        $('#tiles li .close').on('click', function () {
            var tile = $(this).parent();
            var gridster = $('#tiles').gridster().data('gridster');
            gridster.remove_widget(tile);
        })
    }

    function save () {
        var grid = JSON.stringify($('#tiles').gridster().data('gridster').serialize());

        $.ajax({
            type: "POST",
            url: "@Url.Action("Save")",
            data: grid,
            contentType: "application/json",
            dataType: "json",
            success: function () {
                var alertBox = $('#alert-box');
                alertBox.addClass('alert alert-success');
                alertBox.text('Изменения успешно сохранены!')
                alertBox.fadeIn();
                setTimeout(function () { alertBox.removeClass('alert alert-success').fadeOut() }, 5000);
            }
        })
    }

    function addArticles()
    {
        var ids = [];
        $('.modal-body tbody input:checkbox:checked').each(function () {
            var id = $(this).attr('data-id');
            ids.push(id);
        })
        var gridster = $('#tiles').gridster().data('gridster');

        $.ajax({
            type: "POST",
            url: "@Url.Action("List", "AdArticles")",
            data: JSON.stringify(ids),
            contentType: "application/json",
            dataType: "json",
            success: function (articles) {
                for (var i = 0; i < articles.length;i++)
                {
                    var tags = articles[i]['Tags'];
                    var tagsHtml = '';
                    for (var k = 0; k < tags.length; k++)
                    {
                        tagsHtml += '<span><a href="#"><label> </label>' + tags[k]['Name'] + '</a></span>';
                    }

                    var html = '<li data-id="' + articles[i]['Id'] + '">'
                        + '<button type="button" class="close"><span aria-hidden="true">&times;</span></button>'    
                        + '<img src="'
                        + articles[i]['TitleImagePath'].substring(1)
                        + '">'
                        + '<div class="post-info">'
                        + '<div class="post-basic-info">'
                        + '<h3>'
                        + articles[i]['Title']
                        + '</h3>'
                        + tagsHtml
                        + '<p>'
                        + articles[i]['Body']
                        + '</p>'
                        + '</div> </div> </li>';

                    gridster.add_widget(html, 2, 2);
                }
                SetupCloseButtons();
            }
        })
    }


    function clearGrid() {
        var gridster = $('#tiles').gridster().data('gridster');
        gridster.remove_all_widgets();
    }

    function adjustFontSize(e, ui, $widget) {
        var $content = $widget.children(".post-info");

        var maxHeight = $widget.height() - $content.position().top;

        var ratio = ($widget.height() - $content.position().top) / $content.height();
        var currentFont = $content.css('font-size').split('px')[0];
        var targetFont = currentFont * ratio + 'px';
        $content.css('font-size', targetFont);

        while ($content.height() < maxHeight) {
            currentFont = $content.css('font-size').split('px')[0];
            targetFont = (parseInt(currentFont) + 1) + 'px';
            $content.css('font-size', targetFont);
        }

        while ($content.height() > maxHeight) {
            currentFont = $content.css('font-size').split('px')[0];
            targetFont = (parseInt(currentFont) - 1) + 'px';
            $content.css('font-size', targetFont);
        }
    }


    function loadArticleList(pageNumber) {
        var $body = $('.modal-dialog .modal-body table tbody');
        $body.empty();
        $.ajax({
            type: "POST",
            url: "@Url.Action("PagingList", "AdArticles")",
            data: JSON.stringify({page: pageNumber}),
            contentType: "application/json",
            dataType: "json",
            success: function (data) {
                var articles = data['Articles'];
                var pagingInfo = data['PagingInfo'];
                                
                for(var i = 0; i<articles.length; i++)
                {
                    var $raw = $('<tr>'
                             +'<td>'
                             + '<input type="checkbox" data-id="' + articles[i]['Id'] + '"/>'
                             + '</td>'
                             +'<td>'
                             + articles[i]['Title']
                             + '</td>'
                             + '</tr>');
                   
                    $body.append($raw);
                }

                var $pagingLinks = $('.modal-dialog .pagination');
                $pagingLinks.empty();
                for(var k = 0; k<parseInt(pagingInfo['TotalPages']); k++ )
                {
                    var num = k + 1;
                    var $link = $("<li></li>");
                    if (num == parseInt(pagingInfo['CurrentPage'])) {
                        $link.addClass("active");
                    }
                    $link.html('<a href="#">' + num + '</a>');
                    $pagingLinks.append($link);
                }

                $pagingLinks.children('li').each(function (index) {
                    $(this).click(function (e) {
                        e.preventDefault();
                        loadArticleList(index + 1);
                    });
                })
            }
        })
    }
</script>